#!C:/Program\ Files/Git/usr/bin/sh.exe
echo
exec powershell.exe -NoProfile -ExecutionPolicy Bypass -File ".\hooks\TriggerLocalBuildOnCommit.ps1" -path C:\/Users\/Dmytro_Malohlovets\/git\/captify
exit